name: CD
on:
  push:
    branches: [ master ]

jobs:
  build_and_deploy:
    name: "Build & Deploy"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby, JRuby and TruffleRuby
        uses: ruby/setup-ruby@v1.65.0
        with:
          ruby-version: 2.6.3
      - run: bundle install
      - run: jekyll build
      - name: Upload documentation
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{ secrets.WEBSPACE_HOST }}
          user: ${{ secrets.WEBSPACE_USER }}
          password: ${{ secrets.WEBSPACE_PASSWORD }}
          localDir: "/_site/"
          remoteDir: "."
