name: CD
on:
  push:
    branches: [ master ]

jobs:
  build_and_deploy:
    name: "Build & Deploy"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby, JRuby and TruffleRuby
        uses: ruby/setup-ruby@v1.65.0
        with:
          ruby-version: 2.6.3
          bundler-cache: true
      - name: "Build Blog"
        run: bundle exec jekyll build
        #env: 
        #  JEKYLL_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "Copy Assets"
        run: |
          cp -r assets/.htaccess ./_site/  
          cp -r assets/* ./_site/
      - name: Upload blog
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{ secrets.WEBSPACE_HOST }}
          user: ${{ secrets.WEBSPACE_USER }}
          password: ${{ secrets.WEBSPACE_PASSWORD }}
          localDir: "./_site/"
          remoteDir: "."
